spring:
  application:
    name: shopcart
  main:
    banner: off
  datasource:
    url: jdbc:mysql://localhost:3306/shopcart
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver